POST https://accounts.spotify.com/api/token

Authorization: Basic *<base64 encoded b77963ec1b87492f93abdb8be0ee2977:015556b092bd4936bf6621a312d39392>*
Content-Type: application/x-www-form-urlencoded


grant_type="authorization_code"
code="AQAuLJFdN_d9YwqoYwlvOAcbirQoP2g2Zh6-_T6nOgN0n1H6ci-EOKugO80SgJQusUMQy4B1l093GuGt0ncWQzB-5P2l465YUOikq-_HsgO3x-n4AsjVKJMX1HWf4CkarXjGvERfGs8iUvwjcf-sBJiEVbPUEZHBgT-OuLcpo4ffngvMW4KSjZMsC_lNMs2B2cmaNjacvhNN7yDKzKZpQyPvvghQn6hwLo520mdJpueo-v9pxXNLcvkjqt2PshGX73KdoR_b5MXSyd6TW7P6H3ER0VdYR555Q2W2Q04MkkE-V47ymKZ5oCTteF_dS8UoOphFE-UA1-aIKRv-P9OwzSyVgoLt8Ge-zP1rNrJl6tx0eUDrRFjkeOe7hXkTmt7FacyEpwZS7x-QduENXkMorCIrNYsLKkr-0oyBpfGJhjcnWV1WwOdSZn09801UHdHHQmjmR_aG8O6JrtbStKx7QclxtgmVl9KIDbnSyGaPnzZpKE5Lsn2FPAUptbFbXxRadUUVbXwbh8I0QC2521vmmN2cdsXqdWavVGPTiQWT-BAAYWbyxYtIEjVumxDwnOTWh2bHOIHYDF5mEmzhY6FmWnMDH4cuDnB4O24egrGf7Iri59V2fWkxD6YQ"
redirect_uri="http://localhost:3000/callback"